name: Build ARM Template

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master

      - name: Install Bicep build
        run: |
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/download/v0.14.85/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help

      - name: Run Bicep build
        run: |
            bicep build master/wireguardVPN.bicep
            ls -l master/*.json

      - name: Commit files
        run: |
          cd main
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Automated ARM template build."
          git push github HEAD:${GITHUB_REF}

          